import type { PotholeCase, PotholeSeverity, PotholeStatus } from "./types";

export const POTHOLE_SEVERITY_LABELS: Record<PotholeSeverity, string> = {
  low: "Low",
  medium: "Medium",
  high: "High",
  critical: "Critical",
};

export const POTHOLE_STATUS_LABELS: Record<PotholeStatus, string> = {
  new: "New",
  under_review: "Under review",
  assigned: "Assigned",
  in_progress: "In progress",
  solved: "Solved",
  false_report: "False report",
};

/** Generated pothole demo photos */
const IMG = {
  ph2001: "/mock/potholes/ph-2001.jpg",
  ph2002: "/mock/potholes/ph-2002.jpg",
  ph2003: "/mock/potholes/ph-2003.jpg",
  ph2004: "/mock/potholes/ph-2004.jpg",
  ph2005: "/mock/potholes/ph-2005.jpg",
  ph2006: "/mock/potholes/ph-2006.jpg",
  ph2007: "/mock/potholes/ph-2007.jpg",
  ph2008: "/mock/potholes/ph-2008.jpg",
} as const;

export const MOCK_POTHOLES: PotholeCase[] = [
  {
    id: "ph-2001",
    latitude: 3.0751,
    longitude: 101.5212,
    severity: "high",
    status: "new",
    title: "Deep crater at junction",
    description: "Wide pothole after rain; cars swerving into opposite lane.",
    imageUrl: IMG.ph2001,
    submittedAt: "2026-09-05T08:20:00+08:00",
    responsiblePartyId: "party-mbsa",
    area: "Shah Alam",
    postcode: "40000",
    roadName: "Persiaran Kayangan",
    depthCm: 18,
  },
  {
    id: "ph-2002",
    latitude: 3.1098,
    longitude: 101.6091,
    severity: "medium",
    status: "in_progress",
    title: "Cluster of mid-lane holes",
    description: "Three connected depressions along motorcycle lane.",
    imageUrl: IMG.ph2002,
    submittedAt: "2026-09-02T16:40:00+08:00",
    responsiblePartyId: "party-mbpj",
    area: "Petaling Jaya",
    postcode: "47300",
    roadName: "Jalan SS2/24",
    depthCm: 9,
  },
  {
    id: "ph-2003",
    latitude: 3.0412,
    longitude: 101.4488,
    severity: "critical",
    status: "assigned",
    title: "Edge collapse near drain",
    description: "Road shoulder broken; risk to cyclists at night.",
    imageUrl: IMG.ph2003,
    submittedAt: "2026-09-04T11:05:00+08:00",
    responsiblePartyId: "party-mbk",
    area: "Klang",
    postcode: "41200",
    roadName: "Jalan Sungai Bertam",
    depthCm: 24,
  },
  {
    id: "ph-2004",
    latitude: 3.0524,
    longitude: 101.5882,
    severity: "low",
    status: "under_review",
    title: "Shallow surface break",
    description: "Early-stage alligator cracking forming a shallow hole.",
    imageUrl: IMG.ph2004,
    submittedAt: "2026-09-06T07:15:00+08:00",
    responsiblePartyId: "party-mpsj",
    area: "Subang Jaya",
    postcode: "47500",
    roadName: "Persiaran Tujuan",
    depthCm: 4,
  },
  {
    id: "ph-2005",
    latitude: 3.0866,
    longitude: 101.5355,
    severity: "high",
    status: "solved",
    title: "Repaired bus-lane pothole",
    description: "Hot-mix patch completed; waiting for line marking.",
    imageUrl: IMG.ph2005,
    submittedAt: "2026-08-22T09:30:00+08:00",
    solvedAt: "2026-08-25T14:10:00+08:00",
    responsiblePartyId: "party-mbsa",
    area: "Shah Alam",
    postcode: "40100",
    roadName: "Persiaran Selangor",
    depthCm: 14,
    notes: "Contractor uploaded repair proof.",
  },
  {
    id: "ph-2006",
    latitude: 3.0982,
    longitude: 101.6244,
    severity: "medium",
    status: "new",
    title: "Roundabout entry dip",
    description: "Sudden dip at approach; several near-miss reports.",
    imageUrl: IMG.ph2006,
    submittedAt: "2026-09-06T18:50:00+08:00",
    responsiblePartyId: "party-mbpj",
    area: "Petaling Jaya",
    postcode: "46000",
    roadName: "Bulatan Seksyen 51",
    depthCm: 11,
  },
  {
    id: "ph-2007",
    latitude: 3.0288,
    longitude: 101.6142,
    severity: "critical",
    status: "in_progress",
    title: "Multi-hole stretch",
    description: "Series of holes over 40 m; temporary cones placed.",
    imageUrl: IMG.ph2007,
    submittedAt: "2026-09-01T13:25:00+08:00",
    responsiblePartyId: "party-mpsj",
    area: "Subang Jaya",
    postcode: "47620",
    roadName: "Jalan Puchong–Petaling Jaya",
    depthCm: 21,
  },
  {
    id: "ph-2008",
    latitude: 3.0041,
    longitude: 101.4188,
    severity: "medium",
    status: "solved",
    title: "Port access road patch",
    description: "Heavy lorry wear; resurfaced overnight.",
    imageUrl: IMG.ph2008,
    submittedAt: "2026-08-18T20:00:00+08:00",
    solvedAt: "2026-08-20T06:45:00+08:00",
    responsiblePartyId: "party-mbk",
    area: "Klang",
    postcode: "42000",
    roadName: "Jalan Pelabuhan Utara",
    depthCm: 12,
  },
];

export function getPotholeById(id: string): PotholeCase | undefined {
  return MOCK_POTHOLES.find((p) => p.id === id);
}
